name: aurelian QC

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry Manually
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user poetry
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc

      - name: Install ROBOT CLI
        run: |
          wget https://github.com/ontodev/robot/releases/latest/download/robot.jar -O /usr/local/bin/robot.jar
          echo '#!/bin/bash' | sudo tee /usr/local/bin/robot > /dev/null
          echo 'exec java -jar /usr/local/bin/robot.jar "$@"' | sudo tee -a /usr/local/bin/robot > /dev/null
          sudo chmod +x /usr/local/bin/robot

      - name: Verify ROBOT Installation
        run: robot --version

      - name: Install dependencies
        run: |
          poetry install --no-interaction --extras gradio
          poetry run pip uninstall -y numpy pandas
          poetry run pip install --no-cache-dir numpy pandas
          poetry run pip uninstall bioservices -y || true
          poetry run pip install bioservices

      - name: Run tests (excluding test_agents)
        run: |
          poetry run pytest --maxfail=0 --continue-on-collection-errors || true
